name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Build
      run: wasm-pack build --target web --out-name AutoSimulate --out-dir ./dist/pkg

    - name: Copy index.html
      run: cp index.html ./dist/

    - name: Setup Git
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
    
    - name: Deploy to GitHub Pages
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        cd dist
        git init
        git add -A
        git commit -m "Deploy to GitHub Pages"
        git push -f https://${PAT}@github.com/OmarSiwy/OmarSiwy.github.io.git main:gh-pages
